### PR TITLE
Feature/admin add days to fast button

### PR DESCRIPTION
**Pull request by andylitalo**
**Feature**

Add button to link to form that allows admin to add days by date to an existing fast.
This should speed up creation of weekly fasts (can duplicate an existing weekly fast, then add days with this form).

**Testing**
Try duplicating a weekly fast and adding a few days. Then save and add a few more. Check that they show up on the `Fast`'s entry on the `Fasts` page, as well as that the `Day`s show up associated with that weekly fast.

### CODE REVIEW

**Review by mattash — APPROVED** [review]
Works great. On my screen the help text line breaks weird. I tried to find a quick way to resolve it, but looks like its more than trivial to add custom css to Django admin. Something for later...
Screen Shot 2024-10-21 at 10 02 40 AM

**Comment by andylitalo** [comment]
Yep welcome to Django admin. I fiddled with it on a work project once and gave up so I just accepted defeat this time.

**Comment by mattash** [comment]
Well, its no biggie. Should I merge?

**Comment by andylitalo** [comment]
Merged!

**Pull request merged**
